//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BAA_Task_8.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Shop_BAAEntities : DbContext
    {
        private static Shop_BAAEntities _context;

        public Shop_BAAEntities()
            : base("name=Shop_BAAEntities")
        {
        }
        
        public static Shop_BAAEntities GetContext()
        {
            if (_context == null)
            {
                _context = new Shop_BAAEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Good> Goods { get; set; }
        public virtual DbSet<Sell> Sells { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
